version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    container_name: frontend-container

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    depends_on:
      - mysql
    container_name: backend-container

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_registration
      MYSQL_USER: mayur
      MYSQL_PASSWORD: mayur
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql-container
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-data:
